[goldmark]
[goldmark.extensions.passthrough]
enable = true

[goldmark.extensions.passthrough.delimiters]
block = [["$$", "$$"], ["\\[", "\\]"]]
inline = [["$", "$"], ["\\(", "\\)"]]

[goldmark.renderer]
unsafe = false

[highlight]
style = "github-dark"
lineNos = false
noClasses = false
